### ISSUE TITLE
Hello, hasauino! I have a weird problem when running this rrt_exploration package.

### ISSUE THREAD

**Issue by posanlang** [hasauino/rrt_exploration#1]
I do as you told, and everything goes well. However, when the simulated robot reached one or two goals, it stoped, and stay there without running. The ternimal give some information as showed in the picture. I am wondering if my computer was not powerful enough to run this package? Do you know why this happens?
![2018-03-25 17 21 48](https://user-images.githubusercontent.com/33598479/37873563-c40a710e-3051-11e8-80ec-e94434f7885d.png)

**Comment by hasauino** [comment]
This package doesn't require a powerful computer to run. According to your snapshot, there are no target exploration goals found. This could happen because:
-Map has been full explored (not your case obviously).
-The detectors stopped running.
-filter stopped running.
So when this happens again, can you please see if all these nodes are running and publishing/subscribing normally

**Comment by posanlang** [comment]
Thank you , Hasauino! I have solved my problem, and see the simulated robos running pretty well.

**Comment by posanlang** [comment]
However, i have a new question now.
![2018-03-29 19-31-00](https://user-images.githubusercontent.com/33598479/38086679-dbc077ce-3387-11e8-836b-56c0e8c3a943.png)
As you can see in the picture, the robot seems to be stuck in the upper right corner. How do you see the reason for this happening?

**Comment by yanstreld** [comment]
I have same problem like you,my tree do not grow or grow in a small area density.


![selection_009](https://user-images.githubusercontent.com/38234677/38533373-9f70b7de-3cab-11e8-98c1-989ad794a266.png)


This problem  not only appear in simulation but also in my real mobile robot. 

![realrobot_rrt_problem](https://user-images.githubusercontent.com/38234677/38533667-f1d4958a-3cac-11e8-9ef9-5be9bffc4bdf.jpg)


but i do not know what problem it is and how to solve it .

**Comment by hasauino** [comment]
Did you assign the area correctly? When you publish the five points which define the area and the starting point, the sequance is important (as indicated in the tutorial)

**Comment by yanstreld** [comment]
Yes,i have assigned the area like video in tutorial, but i do not know what reason caused this result.

(I according to tutorial step by step and nothing changed the code.)

**Comment by hasauino** [comment]
It usually happens when the points sequence is not correct (th sequence is : top-left corner, bottom-left corner, bottom-right corner, top right corner, and finally the initiation point). 
I cannot find amy other reason who would this happen if the area is defined correctly

**Comment by yanstreld** [comment]
Okay,i will try again the points sequence  , i think is wrong about the points sequence.
