### ISSUE TITLE
Rviz Tf error - map is not displayed- Need to couple Tf frames - basefootprint and map

### ISSUE THREAD

**Issue by marcusvinicius178** [hasauino/rrt_exploration#15]
Rviz Tf error - map is not displayed- Need to couple Tf frames - basefootprint and map

Hey I corrected the TF  map error forcing the Transform. Please who wishes to run this pkg properly must add in the "rrt_exploration_tutorials single_simulated_house.launch" launch file the following snippet line:

node pkg="tf" type="static_transform_publisher" name="basefootprint_broadcaster_to_map" args="0 0 0 0 0 0 1 robot_1/map robot_1/base_footprint 100" 

After this you should be able to run it...
Please update your urdf in your github with the right transforms. 
Thanks!

**Comment by marcusvinicius178** [comment]
The snippet is here:

<node pkg="tf" type="static_transform_publisher" name="basefootprint_broadcaster_to_map" args="0 0 0 0 0 0 1 robot_1/map robot_1/base_footprint 100" />

**Comment by hasauino** [comment]
This is wrong, you cannot just set a static frame transformation between the map frame the the robot frame!
The transformation should be published by the SLAM node (I used gmapping package)  you are using (which is not part of this package). 
I will close this issue
