### ISSUE TITLE
Cannot locate message [points] in package [geometry_msgs] 

### ISSUE THREAD

**Issue by YouShaoze** [hasauino/rrt_exploration#20]
When I use VScode edit the CamakeLists or other file (But did not chenge anything!) and catkin_make.
Error :

-- +++ processing catkin package: 'rrt_exploration_tutorials'
-- ==> add_subdirectory(rrt_exploration_tutorials)
-- +++ processing catkin package: 'rrt_exploration'
-- ==> add_subdirectory(rrt_exploration)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Error at /home/ysz/rrt_explore/build/rrt_exploration/cmake/rrt_exploration-genmsg.cmake:3 (message):
  Could not find messages which
  '/home/ysz/rrt_explore/src/rrt_exploration/msg/PointArray.msg' depends on.
  Did you forget to specify generate_messages(DEPENDENCIES ...)?

  Cannot locate message [points] in package [geometry_msgs] with paths
  [['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']]
Call Stack (most recent call first):
  /opt/ros/kinetic/share/genmsg/cmake/genmsg-extras.cmake:307 (include)
  rrt_exploration/CMakeLists.txt:24 (generate_messages)

-- Configuring incomplete, errors occurred!
See also "/home/ysz/rrt_explore/build/CMakeFiles/CMakeOutput.log".
See also "/home/ysz/rrt_explore/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by hasauino** [comment]
I find this very strange!
I don't know what could be the reason
