### ISSUE TITLE
informationGain return 0 always

### ISSUE THREAD

**Issue by Proxeus96** [hasauino/rrt_exploration#25]
hi, i try to implement the package on noetic distro, and the issue that i have is that the function informationGain that is use to the condition that clear centroids always give me 0, and the condition 0.0<0.2 delete the centroids always. i use hector_mapping to get the map, i don't think that this be the problem, if you have idea for the reason to the issues  I would appreciate.
i think that is for this condition
if(mapData.data[i] == -1 and norm(array(point)-point_of_index(mapData, i)) <= r):
                    infoGain += 1
but i don't all the process to get the condition.

**Comment by EdisonPricehan** [comment]
```python
def informationGain(mapData, point, r):
    gain = 0
    resolution = mapData.info.resolution
    width = mapData.info.width
    map_min_x = mapData.info.origin.position.x
    map_min_y = mapData.info.origin.position.y
    center_x = int(floor((point[0] - map_min_x) / resolution))
    center_y = int(floor((point[1] - map_min_y) / resolution))
    r_int = int(r / resolution)
    for idx_y in range(center_y - r_int, center_y + r_int + 1):
        for idx_x in range(center_x - r_int, center_x + r_int + 1):
            idx = idx_y * width + idx_x
            # skip grids out of map
            if idx < 0 or idx >= len(mapData.data):
                continue
            if mapData.data[idx] == -1:
                gain += 1
    return gain * resolution ** 2
```

I met the same problem with you and used this function to give me information gain, which works good. I am on Ubuntu 20.04 btw.

**Comment by ASSANDHOLE** [comment]
> ```python
> def informationGain(mapData, point, r):
>     gain = 0
>     resolution = mapData.info.resolution
>     width = mapData.info.width
>     map_min_x = mapData.info.origin.position.x
>     map_min_y = mapData.info.origin.position.y
>     center_x = int(floor((point[0] - map_min_x) / resolution))
>     center_y = int(floor((point[1] - map_min_y) / resolution))
>     r_int = int(r / resolution)
>     for idx_y in range(center_y - r_int, center_y + r_int + 1):
>         for idx_x in range(center_x - r_int, center_x + r_int + 1):
>             idx = idx_y * width + idx_x
>             # skip grids out of map
>             if idx < 0 or idx >= len(mapData.data):
>                 continue
>             if mapData.data[idx] == -1:
>                 gain += 1
>     return gain * resolution ** 2
> ```
> 
> I met the same problem with you and used this function to give me information gain, which works good. I am on Ubuntu 20.04 btw.

Thanks a lot, this solves my problem.
