### ISSUE TITLE
how to save the map after gmapping？

### ISSUE THREAD

**Issue by longjianquan** [hasauino/rrt_exploration#3]
when i run the command ”rosrun map_server map_saver -f //“,but it show waitting for map.i want to shutdown gampping anytime and how to get(or save) the map.thanks

**Comment by hasauino** [comment]
Did you make sure about the map topic name.
I have recently updated the sim files, map should be published on "map" topic. However, if have the older sim files, map is published on "robot_1/map" topic, so running the map server command without name remapping will not save the map

**Comment by longjianquan** [comment]
![2018-05-18 09-46-31](https://user-images.githubusercontent.com/23145689/41074601-73f5454e-6a3b-11e8-9fbe-048e6968a0bb.png)
when i test on a real turtlebot,it can run simple.launch, but the robot didnt move.  i launch (minimal.launch,,,gmapping_demo.launch,and simple.launch),why?thanks

**Comment by longjianquan** [comment]
![1](https://user-images.githubusercontent.com/23145689/41074771-34261aa0-6a3c-11e8-93b7-9c0d63d6b142.png)
when i test on a real robot,something errors found,the robot didnt move.i only launch(minimal.launch,gmapping.launch and simple.launch),how to solve this problem?thanks
