### ISSUE TITLE
How to launch rrt_exploration package for MiR using simple.launch

### ISSUE THREAD

**Issue by chbloca** [hasauino/rrt_exploration#5]
Hello Hasauino. I am trying to test your package in an industrial mobile robot as part of my thesis. Here, this device launches the navigation stack automatically so the case is slightly different. I managed to run gmapping and it does without problems. So, at this point as everything is set up properly I am trying to launch your package.

I saw that you made the proper modifications for a unique robot so I don't need to make any modifications and mappings of the topics related with robot_1.

So what I've tried so far the following procedure:

From the mir_robot which provides IP bridging, remapping and removing of topics,... stuff that makes possible a good connection between my computer and the robot.

`roslaunch mir_driver mir.launch disable_map:=true`

Now I roslaunch this launcher I have created to execute gmapping, rviz and setting use_sim_time = false:

```
<launch>

  <param name="use_sim_time" value="false" />

  <arg name="scan_topic" default="/f_scan" />

  <node pkg="gmapping" type="slam_gmapping" name="slam_gmapping" output="screen">

    <param name="odom_frame" value="odom"/>
    <param name="base_frame" value="base_link"/>
    <param name="map_frame" value="map"/>

    <!-- Process 1 out of every this many scans (set it to a higher number to skip more scans)  -->
    <param name="throttle_scans" value="1"/>

    <param name="map_update_interval" value="5.0"/> <!-- default: 5.0 -->

    <!-- The maximum usable range of the laser. A beam is cropped to this value.  -->
    <param name="maxUrange" value="5.0"/>

    <!-- The maximum range of the sensor. If regions with no obstacles within the range of the sensor should appear as free space in the map, set maxUrange < maximum range of the real sensor <= maxRange -->
    <param name="maxRange" value="10.0"/>

    <param name="sigma" value="0.05"/>
    <param name="kernelSize" value="1"/>
    <param name="lstep" value="0.05"/>
    <param name="astep" value="0.05"/>
    <param name="iterations" value="5"/>
    <param name="lsigma" value="0.075"/>
    <param name="ogain" value="3.0"/>
    <param name="minimumScore" value="0.0"/>
    <!-- Number of beams to skip in each scan. -->
    <param name="lskip" value="0"/>

    <param name="srr" value="0.01"/>
    <param name="srt" value="0.02"/>
    <param name="str" value="0.01"/>
    <param name="stt" value="0.02"/>

    <!-- Process a scan each time the robot translates this far  -->
    <param name="linearUpdate" value="0.1"/>

    <!-- Process a scan each time the robot rotates this far  -->
    <param name="angularUpdate" value="0.05"/>

    <param name="temporalUpdate" value="0.1"/>
    <param name="resampleThreshold" value="0.5"/>

    <!-- Number of particles in the filter. default 30        -->
    <param name="particles" value="10"/>

    <!-- Initial map size  -->
    <param name="xmin" value="-10.0"/>
    <param name="ymin" value="-10.0"/>
    <param name="xmax" value="10.0"/>
    <param name="ymax" value="10.0"/>

    <!-- Processing parameters (resolution of the map)  -->
    <param name="delta" value="0.02"/>

    <param name="llsamplerange" value="0.01"/>
    <param name="llsamplestep" value="0.01"/>
    <param name="lasamplerange" value="0.005"/>
    <param name="lasamplestep" value="0.005"/>

    <remap from="scan" to="$(arg scan_topic)"/>
  </node>

  <node pkg="rviz" type="rviz" name="rviz" />

</launch>
```

And finally the last thing I do is:

`roslaunch rrt_exploration simple.launch`

The problem comes when I try to publish the points in RViz, there won't appear any of them RViz so they won't be published and your algorithm won't run. What am I doing wrong?

**Comment by hasauino** [comment]
Hi chbloca,
I would first check the topic names on which Rviz publishes clicked points, which you use to define the area. The global and local detectors expect the points to be published on ```/clicked_point```. This topic is by default the topic name Rviz publishes any clicked point. Most likely this is not your problem.

The second thing you need to check, whether you visualize  ```Markers``` on Rviz. The detectors publish ```Marker``` messages on ```/global_detector_shapes``` and ``` /local_detector_shapes```.

I have added a [launch file](https://github.com/hasauino/rrt_exploration_tutorials/blob/master/launch/simple.launch) in the rrt_exploration_tutorials package, for launching a robot without name prefix. It uses a [Rviz config file](https://github.com/hasauino/rrt_exploration_tutorials/blob/master/launch/includes/rviz_config/simple.rviz) to visualize everything correctly. You may need to make changes according to your topic names.

If the problem still persists, can you show me all the topic names when you run your system?

**Comment by chbloca** [comment]
I just added this line in the launcher I posted:
```
<node pkg="rviz" type="rviz" name="rviz" args="-d $(find rrt_exploration_tutorials)/launch/includes/rviz_config/simple.rviz">
  </node>
```
Now with the RViz running your custom configuration it works! Just the rrt algorithm, but the robot won't move.
<img width="1015" alt="sketch" src="https://user-images.githubusercontent.com/45597426/50043218-e932b200-0078-11e9-8da6-135bcf114351.png">
Here are the list of topics:
<img width="293" alt="c" src="https://user-images.githubusercontent.com/45597426/50043222-f2bc1a00-0078-11e9-9239-71538d0d5608.png">
<img width="206" alt="b" src="https://user-images.githubusercontent.com/45597426/50043223-f51e7400-0078-11e9-8564-4f07890788f5.png">
Are the command move orders based on 2D Nav Goal? Because when I try to send orders manually to the robot with 2D Nav Goal, it won't move. Maybe that's the problem. So if I manage to solve this, will it work? Or what might be another problem?
Thanks for your quick answer, Hasauino.

**Comment by hasauino** [comment]
Can you also show me your tf tree, all the frames?

**Comment by chbloca** [comment]
I will try to answer your questions and provide your the rosservice list tomorrow when I have access again to the robot.
Meanwhile, here I provide you the tf tree and the frames.
![rosgraph full with launcher](https://user-images.githubusercontent.com/45597426/50046518-62e49300-00ad-11e9-84fa-c12a343ef246.png)
![rosgraph with launcher](https://user-images.githubusercontent.com/45597426/50046523-71cb4580-00ad-11e9-88a9-8e795c1cdd93.png)
[frames with launcher.pdf](https://github.com/hasauino/rrt_exploration/files/2682985/frames.with.launcher.pdf)

**Comment by chbloca** [comment]
Here is the rosservice list:
<img width="208" alt="1" src="https://user-images.githubusercontent.com/45597426/50052638-b4356680-012f-11e9-8a4f-8bf60ccf11f6.png">
The topic used to send Nav goal is: /move_base_simple/goal
move_base action is for the navigation stack
relative_move_action is a feature built-in the robot which provides the posibility of moving it with a virtual joystick as if it was a "rosrun teleop_twist_keyboard teleop_twist_keyboard.py" but smoother.

**Comment by hasauino** [comment]
Hi chbloca,
It looks like both the ```filter``` and the ```assigner``` nodes are not running. I first will list what both of these nodes depend on. Then I will try to expect what your setup is missing.

###### 1-Filter node:
It depends on:
- Global cost maps, which the navigation stack should be publishing.
the cost maps are expected to be published on ```/move_base_node/global_costmap/costmap```.
- Map.

###### 2-Assigner node:
it depends on:
- Map.
- tf: 
 >- /base_link to be the robot frame
>- a transformation between /map frame to /base_link. 
- ```/move_base``` action server. Which is normally run by the navigation stack.
- ```/move_base_node/NavfnROS/make_plan service```. Also run by the navigation stack.

###### What I think is missing in your setup:
- Global costmap.
 are you sure it's being published? if so, is it on the same topic name ```/move_base_node/global_costmap/costmap```? why is it marked orange in Rviz, indicating a warning or error.
If there is no problem with the global costmap, the filter node should be running. The only possible reason why it's not is the global cost map.

-```/move_base_node/NavfnROS/make_plan``` service. 
In your ```rosservice list``` it was not there. I also don't see other navigation stack services. They are not required though.

-Regarding the ```move_base``` action. You said you were not able to send a Nav goal manually. This is strange, since Rviz publishes on the ```/move_base_simple/goal ``` topic too. If the move_base action is running correctly, you should be able to send Nav goals. Try to check tool properties of Rviz, and check 2D Nav goal topic if it's set correctly.

![alt text](https://github.com/hasauino/storage/blob/master/pictures/tools_properties.png "Rviz tools properties panel")

**Comment by hasauino** [comment]
Ok great!   :thumbsup:
glad it finally worked. I will close this issue now.
thanks for providing this launch file, I think it might be helpful for others running through the same problem
