### ISSUE TITLE
No frontier point is detected

### ISSUE THREAD

**Issue by GuillermoROS** [hasauino/rrt_exploration#8]
Hello,

Once I have followed all the steps indicated on the website to use the RRT exploration algorithm in turtlebot 2, everything runs correctly without giving any error (see attached photos), but the frontier points are not detected. However, I proceeded to make a rostopic echo /detected_points and effectively no information arrived.

To make sure I wasn't doing anything wrong, I installed the rrt_exploration_tutorials package along with the rest of the requirements. I followed all the steps you indicate on the web ( http://wiki.ros.org/rrt_exploration/Tutorials/singleRobot_exploration/Tutorials/singleRobot) and It didn't detect any points either.

Could you please tell me what this may be due to?

Thank you very much in advance

Pd: we are using an Nvidia Jetson TX2

![rrt_exploration_1](https://user-images.githubusercontent.com/53112372/61576819-f2886f00-aade-11e9-9ed3-51e40e481c98.png)
![rrt_exploration_2](https://user-images.githubusercontent.com/53112372/61576820-f2886f00-aade-11e9-8efe-c4dfad439197.png)
![rrt_exploration_3](https://user-images.githubusercontent.com/53112372/61576821-f3210580-aade-11e9-92a1-ae7b55529141.png)

**Comment by hasauino** [comment]
Hi, sorry for the late reply.

**Comment by GuillermoROS** [comment]
Hello,
I'm also sorry for the delay. I've been away for few days so I couldn't answer until today.
Attached are photos of the lists you asked for.
Thanks!
![rosnode_list](https://user-images.githubusercontent.com/53112372/64183056-859c1f00-ce69-11e9-8378-9c96d023fc5e.png)
![rostopic_list_1](https://user-images.githubusercontent.com/53112372/64183082-92207780-ce69-11e9-9788-bf99da242631.png)
![rostopic_list_2](https://user-images.githubusercontent.com/53112372/64183095-9ba9df80-ce69-11e9-889b-9bb698a77ea8.png)

**Comment by ZwoeleMan** [comment]
Hi! Exactly the same issue here; costmap is correct and visually, the algorithm is clearly detecting frontiers as the RRT is progressing and stopping at known map boundaries. However, nothing is published on /detected_points. 

The issue is present on both the global, local and opencv detector.

Are there any workarounds available atm?

**Comment by MuhammadDanyialKhan** [comment]
Hi! I have the same issue here, frontier points are not detected, as you can see [here](https://drive.google.com/file/d/1WzwOazv2fWZuEk3vKAeIY4Bzw9HUbDmq/view?usp=sharing)
Other nodes are working fine, like gmapping, move base and map merge. I am using hector quadrotor package. I do not know what to do next, please guide me through this problem.

**Comment by hasauino** [comment]
@MuhammadDanyialKhan 
sorry for the late reply, did you figure out the problem?
if not, did you publish the five points that declare the region of exploration and the start point for the global detector?

**Comment by davidlmljll** [comment]
The ObstacleFree function in functions.cpp uses the char type to determine map occupation. On embedded TX2, the char type is unsigned, so the boundary values returned by the detector are all 0, and the boundary points cannot be detected!
